### ISSUE TITLE
Final Project

### ISSUE THREAD

**Issue by skyzh** [SkyZH/Hurricane#1]
![mr4js8y7rrgl0apwn7sytq_thumb_5d22](https://user-images.githubusercontent.com/4198311/50549040-40e43680-0c91-11e9-8176-afe08dcd839e.jpg)
![byvrruayqjucbo0 yjd6pw_thumb_5d21](https://user-images.githubusercontent.com/4198311/50549042-4477bd80-0c91-11e9-8200-d59d6488627e.jpg)

**Comment by danyang685** [comment]
Good job!

**Comment by skyzh** [comment]
![image](https://user-images.githubusercontent.com/4198311/50835934-ec2c7400-1392-11e9-8885-8579f30b7837.png)
